application:
  name: Visual Smilei
  version: 0.0.1

server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    smilei:
      driverClassName: "org.postgresql.Driver"
      jdbcUrl:  "jdbc:postgresql://localhost:5432/smilei-db"
      username: postgres
      password: postgres
      poolSize: 50
      initialSize: 50
      minIdle: 1
      maxIdle: 1
      maxActive: 20